### ISSUE TITLE
Stop login button getting bigger

### ISSUE THREAD

**Issue by stubbo** [HexaneNetworks/gamepanel-dev#19]
**Is your feature request related to a problem? Please describe.**
Not really needed its just i personally think it does not look very good

**Describe the solution you'd like**
Remove the 
```CSS
.Button:hover{
    border: solid 1px #E4E2E9;
}
```
**Describe alternatives you've considered**
Me putting up with it
