### ISSUE TITLE
Menu bar wrong margin size

### ISSUE THREAD

**Issue by stubbo** [HexaneNetworks/gamepanel-dev#34]
**Describe the bug**
Some bars are not setting width correctly

**To Reproduce**
Go to a sub user page

**Screenshots**
![wow](https://img.stubbo.me/epwo8) (left side has margin and right does not)

**Additional context**
using a calc in the css to set the width better for fitting the area 
```css
#ctl00_ContentPlaceHolderMain_SubUsers1_GridUsers_TabToolBar1_RadToolBar1 {
  width: calc(100% - 20px)
}
```
Think it will be best to adjust this in the style attribute where the current width is set.
